export const projects = [
  {
    id: 1,
    img: "",
    title: "FuelCore AI",
    subtitle: "AI-Powered Nutrition App",
    text: "Comprehensive nutrition app with questionnaires, meal plans, and AI-generated recipes using Gemini API. Advanced UX with personalized recommendations.",
    link: "https://v0-nutri-plan.vercel.app/",
    github: "https://github.com/deruvodaniel/nutri-plan-ai",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/hGn33GSV/Captura-de-pantalla-2025-11-12-150847.png",
    title: "UX dev Game",
    subtitle: "Coder vs IA game",
    text: "Gamified coding/tech learning experience where developers battle against programming-related enemies in a card-based RPG system.",
    link: "https://ux-dev-game-lemon.vercel.app/",
    github: "https://github.com/deruvodaniel/ux-dev-game",
  },
  {
    id: 3,
    img: "",
    title: "UX Developer Challenge",
    subtitle: "Technical Interview Assessment",
    text: "This is a technical interview challenge designed to assess UX Developer candidates' skills in building responsive, accessible, and well-architected user interfaces. I developed this challenge to evaluate candidates during the interview process for senior UX Developer positions.",
    link: "https://ux-dev-candidates-challenge.vercel.app/",
    github: "",
  },
  {
    id: 4,
    img: "",
    title: "AI Sticker Generator",
    subtitle: "OpenAI, Supabase & n8n Integration",
    text: "The app generates AI stickers (OpenAI), optionally integrates a selfie via image edits, composites overlays on the client, uploads final images to Supabase storage, and notifies workflows via n8n webhooks.",
    link: "https://sticker-generator-tan.vercel.app/",
    github: "",
  },
  {
    id: 5,
    img: "",
    title: "Dragon Ball API App",
    subtitle: "React, API Integration, Mobile First",
    text: "App that connects to external API with theme switching and translations. Mobile-first responsive design with modern UI components.",
    link: "https://v0-dragon-ball-api-app.vercel.app/",
    github: "https://github.com/deruvodaniel/dragon-ball-api-app",
  },
  {
    id: 6,
    img: "",
    title: "Monster Game",
    subtitle: "Vue.js Interactive Game made with IA",
    text: "Engaging browser game built with Vue.js featuring dynamic gameplay mechanics and responsive design.",
    link: "https://deploy-preview-4--monster-game-vuejs.netlify.app/",
    github: "https://github.com/deruvodaniel/Monster-Game",
  },
  {
    id: 7,
    img: "",
    title: "Modern Ecommerce",
    subtitle: "Next.js, Shopify Integration",
    text: "Full-featured ecommerce platform with modern design, payment integration, and inventory management. Built with Next.js and Shopify.",
    link: "https://v0-shopify-ecommerce-setup-56.vercel.app/",
    github: "https://github.com/deruvodaniel/modern-ecommerce",
  },
  {
    id: 8,
    img: "",
    title: "Production‑Ready UI (Atomic Design)",
    subtitle: "Next.js 13 App Router, Tailwind, TypeScript, Storybook, Jest/RTL",
    text: "Starter de Next.js 13 (App Router) + Tailwind + TypeScript, listo para producción, con arquitectura atómica (atoms/molecules/organisms) y ThemeProvider con design tokens personalizables. Componentes accesibles estilo Radix/shadcn, Storybook con documentación y ejemplos (build servido en /storybook), tests con Jest/RTL y utilidades para UI consistente. Mejoras aplicadas para SEO/Performance/A11y.",
    link: "https://production-ready-ui-atomic-design.vercel.app/",
    github: "https://github.com/deruvodaniel/production-ready-ui-atomic-design",
  },
  {
    id: 9,
    img: "https://i.postimg.cc/jdrLHr4J/Screenshot-7.png",
    title: "Forkify App",
    subtitle: "Search 10000+ Recipes",
    text: "Advanced recipes application using vanilla JavaScript, modern fetch API, and object-oriented programming principles.",
    link: "https://forkify-olive.vercel.app/",
    github: "https://github.com/deruvodaniel/forkify",
  },
  {
    id: 10,
    img: "https://i.postimg.cc/JhjVVWdq/Screenshot-9.png",
    title: "Social Media Dashboard",
    subtitle: "HTML, SASS, JavaScript",
    text: "Interactive dashboard with real-time data visualization and modern UI components.",
    link: "https://cheerful-macaron-52607c.netlify.app/",
    github: "https://github.com/deruvodaniel/MakingSenseChallenge",
  },
  {
    id: 11,
    img: "https://i.postimg.cc/ht2vRQW9/Screenshot-6.png",
    title: "GDLWEBCAMP",
    subtitle: "Event Management App",
    text: "Interactive event management application with modern JavaScript and responsive design.",
    link: "https://deruvodaniel.github.io/GDLWEBCAMP/",
    github: "https://github.com/deruvodaniel/GDLWEBCAMP",
  },
];
