export const projects = [
  {
    id: 1,
    img: "https://i.postimg.cc/jdrLHr4J/Screenshot-7.png",
    title: "Forkify app",
    subtitle: "Search all over 10000+ recipes",
    text: "Recipes app using vainilla Javascript, fetch, OOP",
    link: "https://forkify-olive.vercel.app/",
    github: "https://github.com/deruvodaniel/forkify",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/GtDTcLJb/Screenshot-1.png",
    title: "Monster Game",
    subtitle: "Simple Game created with Vue.js",
    text: "You have to kill the monster, but be careful you can die too!",
    link: "https://deruvodaniel.github.io/Monster-Game/",
    github: "https://github.com/deruvodaniel/Monster-Game",
  },
  {
    id: 3,
    img: "https://i.postimg.cc/NjsFn7Vs/Screenshot-4.png",
    title: "Vue Landing page (IbisDev)",
    subtitle: "Vue, SASS, Responsive",
    text: "Landing page developed for challenge in Vue.js",
    link: "https://ibis-dev-challenge.vercel.app/",
    github: "https://github.com/deruvodaniel/ibisDev-Challenge",
  },
  {
    id: 4,
    img: "https://i.postimg.cc/Z54vSh9h/Screenshot-5.png",
    title: "Vue Users table (NewCombin)",
    subtitle: "Users form, data table components, API, Sass",
    text: "Practice challenge for NewCombine",
    link: "https://new-combin-challenge.vercel.app/",
    github: "https://github.com/deruvodaniel/NewCombinChallenge",
  },
  {
    id: 5,
    img: "https://i.postimg.cc/yx0xMfsd/Screenshot-2.png",
    title: "Tejas Verdes",
    subtitle: "Landing Page for nursing home",
    text: "HTML, CSS, Boostrap, Php",
    link: "https://www.tejasverdes.com.ar/",
    github: "https://github.com/deruvodaniel/tejasVerdes",
  },
  {
    id: 6,
    img: "https://i.postimg.cc/FHpdFnck/Screenshot-3.png",
    title: "Psychologist landing page",
    subtitle: "Simple Landing page",
    text: "HTML, SASS, Bootstrap, SEO, Responsive",
    link: "https://deruvodaniel.github.io/piscologo-lp-bootstrap/",
    github: "https://github.com/deruvodaniel/piscologo-lp-bootstrap",
  },
  {
    id: 7,
    img: "https://i.postimg.cc/ht2vRQW9/Screenshot-6.png",
    title: "GDLWEBCAMP",
    subtitle: "Practice app Javascript",
    text: "App developed with HTML, CSS, Jquery, Javascript",
    link: "https://deruvodaniel.github.io/GDLWEBCAMP/",
    github: "https://github.com/deruvodaniel/GDLWEBCAMP",
  },
];
