export const projects = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop",
    title: "FuelCore AI",
    subtitle: "AI-Powered Nutrition App",
    text: "Comprehensive nutrition app with questionnaires, meal plans, and AI-generated recipes using Gemini API. Advanced UX with personalized recommendations.",
    link: "https://v0-nutri-plan.vercel.app/",
    github: "https://github.com/deruvodaniel/nutri-plan-ai",
  },
  {
    id: 2,
    img: "https://i.postimg.cc/hGn33GSV/Captura-de-pantalla-2025-11-12-150847.png",
    title: "UX dev Game",
    subtitle: "Coder vs IA game",
    text: "gamified coding/tech learning experience where developers battle against programming-related enemies in a card-based RPG system.",
    link: "https://ux-dev-game-lemon.vercel.app/",
    github: "https://github.com/deruvodaniel/ux-dev-game",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop",
    title: "Dragon Ball API App",
    subtitle: "React, API Integration, Mobile First",
    text: "App that connects to external API with theme switching and translations. Mobile-first responsive design with modern UI components.",
    link: "https://v0-dragon-ball-api-app.vercel.app/",
    github: "https://github.com/deruvodaniel/dragon-ball-api-app",
  },
  {
    id: 8,
    img: "https://i.postimg.cc/GtDTcLJb/Screenshot-1.png",
    title: "Monster Game",
    subtitle: "Vue.js Interactive Game made with IA",
    text: "Engaging browser game built with Vue.js featuring dynamic gameplay mechanics and responsive design.",
    link: "https://deruvodaniel.github.io/Monster-Game/",
    github: "https://github.com/deruvodaniel/Monster-Game",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
    title: "Modern Ecommerce",
    subtitle: "Next.js, Shopify Integration",
    text: "Full-featured ecommerce platform with modern design, payment integration, and inventory management. Built with Next.js and Shopify.",
    link: "https://v0-shopify-ecommerce-setup-56.vercel.app/",
    github: "https://github.com/deruvodaniel/modern-ecommerce",
  },
  {
    id: 11,
    img: "https://images.unsplash.com/photo-1529101091764-c3526daf38fe?w=1200&h=630&fit=crop",
    title: "Production‑Ready UI (Atomic Design)",
    subtitle: "Next.js 13 App Router, Tailwind, TypeScript, Storybook, Jest/RTL",
    text: "Starter de Next.js 13 (App Router) + Tailwind + TypeScript, listo para producción, con arquitectura atómica (atoms/molecules/organisms) y ThemeProvider con design tokens personalizables. Componentes accesibles estilo Radix/shadcn, Storybook con documentación y ejemplos (build servido en /storybook), tests con Jest/RTL y utilidades para UI consistente. Mejoras aplicadas para SEO/Performance/A11y.",
    link: "https://production-ready-ui-atomic-design.vercel.app/",
    github: "https://github.com/deruvodaniel/production-ready-ui-atomic-design",
  },
  {
    id: 5,
    img: "https://i.postimg.cc/jdrLHr4J/Screenshot-7.png",
    title: "Forkify App",
    subtitle: "Search 10000+ Recipes",
    text: "Advanced recipes application using vanilla JavaScript, modern fetch API, and object-oriented programming principles.",
    link: "https://forkify-olive.vercel.app/",
    github: "https://github.com/deruvodaniel/forkify",
  },
  {
    id: 6,
    img: "https://i.postimg.cc/NjsFn7Vs/Screenshot-4.png",
    title: "Vue Landing Page",
    subtitle: "Vue.js, SASS, Responsive",
    text: "Professional landing page developed with Vue.js, featuring modern animations and responsive design patterns.",
    link: "https://ibis-dev-challenge.vercel.app/",
    github: "https://github.com/deruvodaniel/ibisDev-Challenge",
  },
  {
    id: 7,
    img: "https://i.postimg.cc/JhjVVWdq/Screenshot-9.png",
    title: "Social Media Dashboard",
    subtitle: "HTML, SASS, JavaScript",
    text: "Interactive dashboard with real-time data visualization and modern UI components.",
    link: "https://cheerful-macaron-52607c.netlify.app/",
    github: "https://github.com/deruvodaniel/MakingSenseChallenge",
  },
  {
    id: 9,
    img: "https://i.postimg.cc/ht2vRQW9/Screenshot-6.png",
    title: "GDLWEBCAMP",
    subtitle: "Event Management App",
    text: "Interactive event management application with modern JavaScript and responsive design.",
    link: "https://deruvodaniel.github.io/GDLWEBCAMP/",
    github: "https://github.com/deruvodaniel/GDLWEBCAMP",
  },
];
