export const technologies = [
  { id: 1, img: null, text: 'React' },
  { id: 2, img: null, text: 'Next.js' },
  { id: 3, img: null, text: 'Vue.js' },
  { id: 4, img: null, text: 'JavaScript' },
  { id: 5, img: null, text: 'TypeScript' },
  { id: 6, img: null, text: 'AI Tools' },
  { id: 7, img: null, text: 'Tailwind CSS' },
  { id: 8, img: null, text: 'Radix UI' },
  { id: 9, img: null, text: 'Storybook' },
  { id: 10, img: null, text: 'MUI' },
  { id: 11, img: null, text: 'Styled Components' },
  { id: 12, img: null, text: 'Sass' },
  { id: 13, img: null, text: 'CSS Modules' },
  { id: 14, img: null, text: 'Cypress' },
  { id: 15, img: null, text: 'Jest' },
  { id: 16, img: null, text: 'Git' },
  { id: 17, img: null, text: 'Docker' },
  { id: 18, img: null, text: 'CI/CD' },
  { id: 19, img: null, text: 'Figma' },
  { id: 20, img: null, text: 'A11y / SEO / Analytics' },
];
